--- 
- merb-core (= 1.0.3, runtime)
- extlib (>= 0.9.8, runtime)
- erubis (>= 2.6.2, runtime)
- rake (>= 0, runtime)
- json_pure (>= 0, runtime)
- rspec (>= 0, runtime)
- rack (>= 0, runtime)
- mime-types (>= 0, runtime)
- thor (>= 0.9.7, runtime)
- webrat (>= 0.3.1, development)
- maruku (>= 0.5.9, runtime)
- merb-assets (= 1.0.3, runtime)
